config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :inventories
  resources :reviews
  root 'mainpages#index'

  namespace :admin do
    resources :brands
    resources :brand_models
    resources :cms_categories
    resources :reviews
  end



  resources :carts
  resources :cart_checkouts
  resources :wheels
  resources :tires do 
    get :tire_brands, on: :collection
  end

  resources :users

  post "/hook" => "cart_checkouts#hook"
  post "/cart_checkouts/:id" => "cart_checkouts#show"

 
  get 'mainpages/update_years', :as => 'update_years'
  get 'mainpages/update_makes', :as => 'update_makes'
  get 'mainpages/update_models', :as => 'update_models'
  get 'mainpages/update_options', :as => 'update_options'

  get 'mainpages/update_aspectratio', :as => 'update_aspectratio'
  get 'mainpages/update_rimdiameter', :as => 'update_rimdiameter'
  get 'mainpages/update_wheelwidth', :as => 'update_wheelwidth'

  get 'mainpages/search_tires', :as => 'search_tires'
  get 'mainpages/search_wheels', :as => 'search_wheels'
  get 'mainpages/search_wheels_tires', :as => 'search_wheels_tires' 
  get 'mainpages/search_entry', :as => 'search_entry'
  get 'mainpages/list_all_tires', :as => 'list_all_tires'
  get 'mainpages/list_all_wheels', :as => 'list_all_wheels'
  get 'mainpages/search_locations', :as => 'search_locations'
  get 'mainpages/product_page', :as => 'product_page'
  get 'mainpages/search_by_size', :as => 'search_by_size'
  get 'mainpages/list_wheels_tires', :as => 'list_wheels_tires'
  get 'mainpages/compare_price', :as => 'compare_price'
  get 'mainpages/comparison', :as => 'comparison'

  # for tires and wheels per brand search
  get 'mainpages/tires_per_brand_list', :as => 'tires_per_brand_list'
  

  # get 'mainpages/cart', :as => 'cart'
  get '/brands', :to => redirect('/brands.html')

  # for user signup
  # get 'users/new', :as => 'signup'

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
	before_filter :set_brand, only: [:show, :update, :destroy]

  def index
    @brands = Brand.paginate(:page => params[:page], :per_page => 20)
  end

  def new
  	@brand = Brand.new
  end
  
  def edit
  	@brand = Brand.find params[:id]
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def create
  	brand = Brand.new(brand_params)

    if brand.save
      flash[:success] = 'Entry was successfully created.'
      redirect_to admin_brands_path
    else
      flash[:error] = 'An error occured while creating new brand.'
      render 'new'
    end
  end

  def update
  	brand = Brand.find params[:id]
    if brand.update(brand_params)
      flash[:success] = 'Entry was successfully updated.'
      redirect_to admin_brands_path
    else
      flash[:error] = 'An error occured while creating new brand.'
      render 'new'
    end
  end
  
  def destroy
  	brand = Brand.find params[:id]
    brand.destroy!
    flash[:success] = 'Entry has been deleted.' 
    redirect_to admin_brands_path
  end

  private

    def set_brand
      @brand = Brand.find(params[:id])
    end
      
    def brand_params
      params.require(:brand).permit(:brand_name, :abbr, :logo, :status, :product_type )
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/admin/brands/index.html.slim
= render "layouts/sidemenu"      

main.col-md-9.ml-sm-auto.col-lg-10.px-4 role="main" 
  .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pt-3.pb-2.mb-3.border-bottom
    h1.h2 Brands
    .btn-toolbar.mb-2.mb-md-0
      = link_to "Create Entry", new_admin_brand_path, class: "btn btn-sm btn-outline-secondary"
      | &nbsp;
      .btn-group.mr-2
        button.btn.btn-sm.btn-outline-secondary Share
        button.btn.btn-sm.btn-outline-secondary Export
  br
  .table-responsive
    table.table.table-striped.table-sm
      thead
        tr
          th ID
          th Brand Name
          th Abbr
          th Status
          th Product Type
          th
      tbody
        - @brands.each  do |brand|
          tr
            td = brand.id
            td = brand.brand_name
            td = brand.abbr
            td = brand.status
            td = brand.product_type
            td
              = link_to 'Edit', edit_admin_brand_path(brand), class: 'btn btn-sm btn-outline-info'
              | &nbsp;
              = link_to 'Delete', admin_brand_path(brand), method: :delete, 'data-confirm' => 'Are you sure you want to delete this entry?', class: 'btn btn-sm btn-outline-danger'
      tfoot
        tr
          td colspan=6
            = will_paginate @brands
               