config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :inventories
  resources :reviews
  root 'mainpages#index'

  namespace :admin do
    resources :brands
    resources :brand_models
    resources :cms_categories
    resources :reviews
  end



  resources :carts
  resources :cart_checkouts
  resources :wheels
  resources :tires do 
    get :tire_brands, on: :collection
  end

  resources :users

  post "/hook" => "cart_checkouts#hook"
  post "/cart_checkouts/:id" => "cart_checkouts#show"

 
  get 'mainpages/update_years', :as => 'update_years'
  get 'mainpages/update_makes', :as => 'update_makes'
  get 'mainpages/update_models', :as => 'update_models'
  get 'mainpages/update_options', :as => 'update_options'

  get 'mainpages/update_aspectratio', :as => 'update_aspectratio'
  get 'mainpages/update_rimdiameter', :as => 'update_rimdiameter'
  get 'mainpages/update_wheelwidth', :as => 'update_wheelwidth'

  get 'mainpages/search_tires', :as => 'search_tires'
  get 'mainpages/search_wheels', :as => 'search_wheels'
  get 'mainpages/search_wheels_tires', :as => 'search_wheels_tires' 
  get 'mainpages/search_entry', :as => 'search_entry'
  get 'mainpages/list_all_tires', :as => 'list_all_tires'
  get 'mainpages/list_all_wheels', :as => 'list_all_wheels'
  get 'mainpages/search_locations', :as => 'search_locations'
  get 'mainpages/product_page', :as => 'product_page'
  get 'mainpages/search_by_size', :as => 'search_by_size'
  get 'mainpages/list_wheels_tires', :as => 'list_wheels_tires'
  get 'mainpages/compare_price', :as => 'compare_price'
  get 'mainpages/comparison', :as => 'comparison'

  # for tires and wheels per brand search
  get 'mainpages/tires_per_brand_list', :as => 'tires_per_brand_list'
  

  # get 'mainpages/cart', :as => 'cart'
  get '/brands', :to => redirect('/brands.html')

  # for user signup
  # get 'users/new', :as => 'signup'

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
	def index
		 @makes = Vehicle.select(:make2).distinct.order('make2 ASC')
		 @years = Vehicle.select(:cyear).distinct.order('cyear DESC')
		 @models = Vehicle.select(:model).distinct.order('model ASC')
		 @options = Vehicle.select(:option2).distinct.order('option2 ASC')
		 
		 @Sectionwidth = TireInventory.select(:Sectionwidth).distinct.order('Sectionwidth DESC')
		 @Aspectratio = TireInventory.select(:Aspectratio).distinct.order('Aspectratio ASC')
		 @Rimdiameter = TireInventory.select(:Rimdiameter).distinct.order('Rimdiameter ASC')
		 @WheelDiameter = WheelInventory.select(:WheelDiameter).distinct.order('WheelDiameter ASC')
		 @WheelWidth = WheelInventory.select(:WheelWidth).distinct.order('WheelWidth ASC')
		 if !params[:search].nil?
		 	# @tires = Tire.where("brand LIKE ? AND model LIKE ?", "%#{params[:make]}%", "%#{params[:model]}%").order("section_width ASC")
		 	@vehicles = Vehicle.select("size_part_1, size_part_2, size_part_3").where({cyear: params['year'], make2: params[:make], model: params[:model], option2: params[:option]}).distinct
		 	
		 	# select size_part_1,size_part_2,size_part_3 from vehicle where cyear = '2018' and make2 = 'Honda' and model = 'Accord' and option2 = 'Sport';
		 end
	end

	def search_entry
			
	end

	def update_makes
		@makes = Vehicle.select('make2').where(cyear: params[:cyear]).distinct.order('make2 ASC').map{|b| [b.make2, b.make2]}
	end

	def update_models
		@models = Vehicle.select('model').where(cyear: params[:cyear]).where(make2: params[:make2]).distinct.order('model DESC').map{|b| [b.model, b.model]}
	end

	def update_options
		@options = Vehicle.select('option2').where(cyear: params[:cyear]).where(make2: params[:make2]).where(model: params[:model]).distinct.order('option2 ASC').map{|b| [b.option2, b.option2]}
	end

	def update_years
		@models = Vehicle.where(make2: params[:make], cyear: params[:year])
		respond_to do |format|
      format.js
    end
	end


	def update_aspectratio
		@Aspectratio = TireInventory.select('Aspectratio').where(Sectionwidth: params[:sectionwidth]).distinct.order('Aspectratio ASC').map{|b| [b.Aspectratio, b.Aspectratio]}
	end

	def update_rimdiameter
		@Rimdiameter = TireInventory.select('Rimdiameter').where({Sectionwidth: params[:sectionwidth], Aspectratio: params[:aspectratio]}).distinct.order('Rimdiameter ASC').map{|b| [b.Rimdiameter, b.Rimdiameter]}
	end

	def update_wheelwidth
		@WheelWidth = WheelInventory.select('WheelWidth').where(WheelDiameter: params[:wheeldiameter]).distinct.order('WheelWidth ASC').map{|b| [b.WheelWidth, b.WheelWidth]}
	end

	def search_by_size
		@cart = Cart.new
		if params[:WheelDiameter].empty?
			@choice = "tires"
			@size = TireSize.select("RAWSIZE").where({SIZE_PART_1: params[:Sectionwidth], SIZE_PART_2: params[:Aspectratio], SIZE_PART_3: params[:Rimdiameter]}).distinct
			@data = StoreInventory.select("mspn, price").where(size: @size.first.RAWSIZE).distinct
			@data2 = StoreInventory.select("mspn").where(size: @size.first.RAWSIZE).distinct.pluck(:mspn)
			@tires_catalogue2 = TireInventory.where(MSPN: @data2)
			# @data = TireInventory.where({Sectionwidth: params[:Sectionwidth], Aspectratio: params[:Aspectratio], Rimdiameter: params[:Rimdiameter]}).paginate(:page => params[:page], :per_page => 10)
			# @data2 = TireInventory.where({Sectionwidth: params[:Sectionwidth], Aspectratio: params[:Aspectratio], Rimdiameter: params[:Rimdiameter]}).pluck(:Brand, :MSPN, :id)
		
			@speedratings = @tires_catalogue2.distinct.pluck(:Speedrating)
		  @load_indexes = @tires_catalogue2.distinct.pluck(:Loadindex1)
		  @sidewallstyles = @tires_catalogue2.distinct.pluck(:Sidewallstyle)
		else
			@choice = "wheels"
			@data = WheelInventory.where({WheelDiameter: params[:WheelDiameter], WheelWidth: params[:WheelWidth]}).distinct
			# @data2 = WheelInventory.where({WheelDiameter: params[:WheelDiameter], WheelWidth: params[:WheelWidth]}).distinct.pluck(:mspn)
			# @speedratings = @data.distinct.pluck(:Speedrating)
		 #  @load_indexes = @data.distinct.pluck(:Loadindex1)
		 #  @sidewallstyles = @data.distinct.pluck(:Sidewallstyle)
		end
	end

	def search_tires
		# @vehicles = Vehicle.select("size_part_1, size_part_2, size_part_3").where({cyear: params['year'], make2: params[:make], model: params[:model], option2: params[:option]}).distinct
		@tgp_sizes = TireSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3, FRB").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		@cartire_ids = TireSize.select("CARTIREID").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct.pluck(:CARTIREID)
		@tgp_plus_sizes = TirePlusSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3").where(CARTIREID: @cartire_ids).distinct
	end

	def search_wheels
		# @tgp_sizes = TireSize.select("CARTIREID").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		# @tgp_mounts = MountWheel.where(CARTIREID: @tgp_sizes).distinct
		# @tgp_plus_sizes = TirePlusSize.select("CARTIREID").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		# @tgp_plus_mounts = MountWheel.where(CARTIREID: @tgp_sizes).distinct

		@tgp_mounts = TireSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		@cartire_ids = TireSize.select("CARTIREID").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct.pluck(:CARTIREID)
		@tgp_plus_mounts = TirePlusSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3").where(CARTIREID: @cartire_ids).distinct

	end

	def search_wheels_tires
		@tgp_sizes = TireSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		@cartire_ids = TireSize.select("CARTIREID").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct.pluck(:CARTIREID)
		@tgp_plus_sizes = TirePlusSize.select("SIZE_PART_1, SIZE_PART_2, SIZE_PART_3, MINRIM, MAXRIM").where(CARTIREID: @cartire_ids).distinct
	end

	def search_locations
		# @zip = Zipcode.where(zipcode: params[:zipcode])
		# @keyword = "#{@zip.first.city.capitalize}, #{@zip.first.state_name}"
		# this should be the actual search via geokit rails
		# @search =Geokit::Geocoders::GoogleGeocoder.geocode(params[:zipcode])
		# @stores = Store.closest(:origin =>[@search.lat, @search.lng]).limit(10)
		
		@stores = Store.limit(15)

		@count_locations = @stores.count(:all)
	end

	def list_all_tires
		# @tires = Tire.where(sectionwidth: params[:sp1], aspectratio: params[:sp2], rimdiameter: params[:sp3])
		if params[:brands].present?
			@brands = params[:brands]
		else
			@brands = ['ACCELERA', 'ACHILLES', 'ARROYO', 'ATTURO', 'BFGOODRICH', 'BRIDGESTONE']
		end

		
		# old list connecting to inventory
		# @size = TireSize.select("RAWSIZE").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		# @inventory_view = StoreInventory.select("mspn, price").where(size: @size.first.RAWSIZE).distinct
		
		# new listing with price in catalogue
		@size = TireSize.select("RAWSIZE").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct
		@inventory_view = TireInventory.where(Sectionwidth: params[:sp1], Aspectratio: params[:sp2], Rimdiameter: params[:sp3])
		# add filter
		@inventory_view = @inventory_view.where(recommended: "yes") if params[:r].present?
		@inventory_view = @inventory_view.where(bestseller: "yes") if params[:b].present?
		@inventory_view = @inventory_view.where(promotions: "yes") if params[:p].present?
		@inventory_view = @inventory_view.where(free_shipping: "yes") if params[:f].present?
		@inventory_view = @inventory_view.order("price ASC")
		# @products.status(params[:status]) if params[:status].present?


		# retain
		@inventory_view2 = StoreInventory.select("mspn").where(size: @size.first.RAWSIZE).distinct.pluck(:mspn)
		@tires_catalogue2 = TireInventory.where(MSPN: @inventory_view2)
		# @tires_catalogue = TireInventory.where(Sectionwidth: params[:sp1], Aspectratio: params[:sp2], Rimdiameter: params[:sp3]).where(Brand: @brands).paginate(:page => params[:page], :per_page => 10)
		# @tires_catalogue2 = TireInventory.where(Sectionwidth: params[:sp1], Aspectratio: params[:sp2], Rimdiameter: params[:sp3]).where(Brand: @brands)
		
		@speedratings = @tires_catalogue2.distinct.pluck(:Speedrating)
		@load_indexes = @tires_catalogue2.distinct.pluck(:Loadindex1)
		@sidewallstyles = @tires_catalogue2.distinct.pluck(:Sidewallstyle)

		@cart = Cart.new
	end

	def list_all_wheels
		@cart = Cart.new
		if params[:add_to_cart] == 'true'
			@wheels_list = WheelInventory.where({WheelDiameter: params[:sp3]})
		else
			@tgp_plus_sizes = TirePlusSize.select("MINRIM, MAXRIM, SIZE_PART_3").where(SIZE_PART_1: params[:sp1], SIZE_PART_2: params[:sp2], SIZE_PART_3: params[:sp3]).distinct
			# @wheels_list = WheelInventory.where(WheelDiameter: @tgp_plus_sizes.first.SIZE_PART_3).where("WheelWidth >= ? AND WheelWidth <= ?", @tgp_plus_sizes.first.MINRIM, @tgp_plus_sizes.first.MAXRIM)
			@wheels_list = WheelInventory.where(WheelDiameter: @tgp_plus_sizes.first.SIZE_PART_3).where(WheelWidth: @tgp_plus_sizes.first.MINRIM..@tgp_plus_sizes.first.MAXRIM)
		end
	end
  
	def list_wheels_tires
		@cart = Cart.new
		@size = TireSize.select("RAWSIZE, SIZE_PART_1, SIZE_PART_2, SIZE_PART_3").where({CYEAR: params['year'], MAKE2: params[:make], MODEL: params[:model], OPTION2: params[:option]}).distinct

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/views/mainpages/_footer.html.slim
footer
  .container
    img src="/images/footer-logo.png" /
    .row
      .col-sm-4
        .footer-inner style=("padding-left: 0;") 
          h2 WHY ONLINE TIRES?
          ul
            li
              a href="promotions.html"  Deals and Rebates
            li
              a href="financing.html"  Financing
            li
              a href="useful-links.html"  Useful Links
            li
              a href="road-hazard-program.html"  Road Hazard Protection
            li
              a href="why-us.html"  Why Us?
            li
              a href="blog.html"  Blogs
      .col-sm-4
        .footer-inner
          h2 DELIVERY INSTALLATION
          ul
            li
              a href="#"  Quick Delivery
            li
              a href="#"  Installer Locator
            li
              a href="#"  Recommended Installers
            li
              a href="#"  Package Installation Instructions
      .col-sm-4
        .footer-inner style=("padding-right: 0;") 
          h2 CUSTOMER SUPPORT
          ul
            li
              a href="contact.html"  Contact Us
            li
              a href="tracking-order.html"  Order Tracking
            li
              a href="key-learnings.html"  Key Learnings
            li
              a href="help-center.html"  Help Center
            li
              a href="faq.html"  FAQs
          h2 style=("color: #d40000; font-size: 28px; font-style: italic; margin-bottom: 20px")  877-465-8473
  .footer-menu-b
    .container
      ul
        li
          a href="terms-services.html"  TERMS OF SERVICES
        li
          a href="privacy-statement.html"  PRIVACY STATEMENT
        li
          a href="return-policy.html"  RETURN POLICY
      .row
        .col-sm-4.align-self-end style=("margin: 0;") 
          img src="/images/footer-b.jpg" /
        .col-sm-8
          .text-right.social-media-a
            a href="#" 
              img src="/images/pin.jpg" /
            a href="#" 
              img src="/images/you.jpg" /
            a href="#" 
              img src="/images/gplus.jpg" /
            a href="#" 
              img src="/images/rss.jpg" /
            a href="#" 
              img src="/images/vimeo.jpg" /
            a href="#" 
              img src="/images/twit.jpg" /
            a href="#" 
              img src="/images/link.jpg" /
            a href="#" 
              img src="/images/fb.jpg" /
.footer-bottom.text-center © 2018 Online Tires. All Rights Reserved.

app/views/mainpages/search_locations.html.slim
= render "header"
.innerpage
  .container
    .row
      .col-sm-12
        .h-title
          h1 STORE LOCATOR
          hr/
        .vr-result-text
          h3
            | Your selected vehicle #{params[:year]} #{params[:make]} #{params[:model]}  #{params[:option]}
            br/
            | Choose from the #{@count_locations} closest store to
            |&nbsp;
            u #{params[:zipcode]}
        .st
          .row
            - counter = 1
            
            

            - @stores.each do |store|
              - if params[:st]
                - @path = search_tires_path(params.merge(str_num: store.store_number))
              - elsif params[:sw]
                - @path = search_wheels_path(params.merge(str_num: store.store_number))
              - else
                - @path = search_wheels_tires_path(params.merge(str_num: store.store_number))
              .col-md-3.st-link
                / a href="after-search-by-vehicle2.html"
                

                = link_to @path
                  .st-inner
                    .st-no = counter
                    h3.text-center #{store.location}
                    .st-a
                      i.fa.fa-map-pin
                      | #{store.Address}, #{store.city}, #{store.state} #{store.zip}
                    .st-p
                      i.fa.fa-phone
                      | #{store.phonenumber}
                    .st-dis
                      | SELECT
              - counter = counter + 1
            
.container
  .h-title
    h1 PROMOTIONS / REBATES
    hr/
  .your-slider
    div
      a href="#" 
        img alt="" src="/images/cslide1.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide2.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide3.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide4.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide5.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide6.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide4.jpg" /
    div
      a href="#" 
        img alt="" src="/images/cslide5.jpg" /
.bottom-banner
  a href="#" 
    img.center-block alt="" src="/images/bottom-banner.jpg" style=("width: 100%;") /
.bottom-banner2
  .container
    .row
      .col-sm-6
        div
          iframe allow=("autoplay; encrypted-media") allowfullscreen="" frameborder="0" height="365" src="https://www.youtube.com/embed/KsSA14uYuTY?rel=0" width="100%" 
      .col-sm-6
        div
          iframe allow=("autoplay; encrypted-media") allowfullscreen="" frameborder="0" height="365" src="https://www.youtube.com/embed/KsSA14uYuTY?rel=0" width="100%" 
.footer-top
  .floating-img
    img src="images/team.png" /
  .container
    h1 CUSTOMER SERVICE
    p Have questions? We are here to help you.
    p
      a.btn.btn-danger href="#"  Contact Us
footer
  .container
    .row
      .col-sm-4
        .footer-inner
          h2 WHY ONLINE TIRES?
          ul
            li
              a href="#"  The Online Tires Advantage
            li
              a href="#"  Our Expertise
            li
              a href="#"  Events & Sponsorships
            li
              a href="#"  Road Hazard Protection
            li
              a href="#"  Careers
      .col-sm-5
        .footer-inner
          h2
            | DELIVERY &
            br>/
            | INSTALLATION
          ul
            li
              a href="#"  Quick Delivery
            li
              a href="#"  Recommended Installers
            li
              a href="#"  Installers' Price Pledge
            li
              a href="#"  Package Installation Instructions
      .col-sm-3
        .footer-inner
          h2 CUSTOMER SUPPORT
          ul
            li
              a href="#"  Contact Us
            li
              a href="#"  Order Tracking
            li
              a href="#"  Warranty Information
            li
              a href="#"  Returns/Refunds
            li
              a href="#"  FAQs
          h2 style=("color: #d40000; font-size: 28px; font-style: italic; margin-bottom: 20px")  877-465-8473
    .footer-menu-b
      ul
        li
          a href="#"  TERMS OF USE
        li
          a href="#"  PRIVACY PLEDGE
        li
          a href="#"  ACCESSIBILITY STATEMENT
      .row
        .col-sm-4
          img src="/images/footer-b.jpg" /
        .col-sm-8
          .text-right.social-media-a
            a href="#" 
              img src="/images/pin.jpg" /
            a href="#" 
              img src="/images/you.jpg" /
            a href="#" 
              img src="/images/gplus.jpg" /
            a href="#" 
              img src="/images/rss.jpg" /
            a href="#" 
              img src="/images/vimeo.jpg" /
            a href="#" 
              img src="/images/twit.jpg" /
            a href="#" 
              img src="/images/link.jpg" /
            a href="#" 
              img src="/images/fb.jpg" /
.footer-bottom.text-center
  | © 2018 Online Tires. All Rights Reserved.
javascript:
  $(function () {
    $('.your-slider').slick({
      dots: false,
      infinite: true,
      speed: 300,
      slidesToShow: 6,
      slidesToScroll: 6,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 4,
            slidesToScroll: 4,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
      ]
    });

    $(".filters").on("click",function(){
      $(this).next().slideToggle();
    });
  });

app/views/mainpages/update_makes.js.erb
$('#make2').html("<%= escape_javascript(options_for_select(@makes)) %>");
$('#make2').attr('disabled',false);
$('#make2').open;


// $('#make2').show();

app/views/mainpages/update_rimdiameter.js.erb
$('#rimdiameter').html("<%= escape_javascript(options_for_select(@Rimdiameter)) %>");

app/views/mainpages/update_wheelwidth.js.erb
$('#wheelwidth').html("<%= escape_javascript(options_for_select(@WheelWidth)) %>");