config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :inventories
  resources :reviews
  root 'mainpages#index'

  namespace :admin do
    resources :brands
    resources :brand_models
    resources :cms_categories
    resources :reviews
  end



  resources :carts
  resources :cart_checkouts
  resources :wheels
  resources :tires do 
    get :tire_brands, on: :collection
  end

  resources :users

  post "/hook" => "cart_checkouts#hook"
  post "/cart_checkouts/:id" => "cart_checkouts#show"

 
  get 'mainpages/update_years', :as => 'update_years'
  get 'mainpages/update_makes', :as => 'update_makes'
  get 'mainpages/update_models', :as => 'update_models'
  get 'mainpages/update_options', :as => 'update_options'

  get 'mainpages/update_aspectratio', :as => 'update_aspectratio'
  get 'mainpages/update_rimdiameter', :as => 'update_rimdiameter'
  get 'mainpages/update_wheelwidth', :as => 'update_wheelwidth'

  get 'mainpages/search_tires', :as => 'search_tires'
  get 'mainpages/search_wheels', :as => 'search_wheels'
  get 'mainpages/search_wheels_tires', :as => 'search_wheels_tires' 
  get 'mainpages/search_entry', :as => 'search_entry'
  get 'mainpages/list_all_tires', :as => 'list_all_tires'
  get 'mainpages/list_all_wheels', :as => 'list_all_wheels'
  get 'mainpages/search_locations', :as => 'search_locations'
  get 'mainpages/product_page', :as => 'product_page'
  get 'mainpages/search_by_size', :as => 'search_by_size'
  get 'mainpages/list_wheels_tires', :as => 'list_wheels_tires'
  get 'mainpages/compare_price', :as => 'compare_price'
  get 'mainpages/comparison', :as => 'comparison'

  # for tires and wheels per brand search
  get 'mainpages/tires_per_brand_list', :as => 'tires_per_brand_list'
  

  # get 'mainpages/cart', :as => 'cart'
  get '/brands', :to => redirect('/brands.html')

  # for user signup
  # get 'users/new', :as => 'signup'

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/brand_content.rb
class BrandContent < ActiveRecord::Base
end

app/models/brand_model.rb
class BrandModel < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	require 'active_shipping'	

	def price=(price)
    if price.is_a?(String)
      formatted_amount = price.to_f
      super(formatted_amount.round(2))
    end
  end

  def origin
    ActiveShipping::Location.new(country: "US", state: "CA", city: "Los Angeles", postal_code: "90001")
  end

  def destination
    # Location.new(country: country, state: state, city: city, postal_code: postal_code)
  	ActiveShipping::Location.new(country: "US", state: "CA", city: "Beverly Hills", postal_code: "90210")
  end

  def packages
    package = ActiveShipping::Package.new(25, [24, 24, 9], units: :imperial)
  end

  def get_rates_from_shipper(shipper)
    response = shipper.find_rates(origin, destination, packages)
    response.rates.sort_by(&:price)
  end

  def ups_rates
    ups = ActiveShipping::UPS.new(login: 'your ups login', password: 'your ups password', key: 'your ups xml key')
    get_rates_from_shipper(ups)
  end

  def fedex_rates
    fedex = ActiveShipping::FedEx.new(login: "119096262", password: "BA92ZG7YpiXH7O2A0dIrJC9Yh", key: "q41znXQdFHQ2cVrJ", account: "510087500", :test => true)
    get_rates_from_shipper(fedex)
  end

  def usps_rates
    usps = ActiveShipping::USPS.new(login: 'your usps account number', password: 'your usps password')
    get_rates_from_shipper(usps)
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/cms_category.rb
class CmsCategory < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/mount_wheel.rb
class MountWheel < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
	RATINGS=[
					[5,5],
					[4,4],
					[3,3],
					[2,2],
					[1,1]
					]
end

app/models/store.rb
class Store < ActiveRecord::Base
	acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

	# reverse_geocoded_by :latitude, :longitude do |obj,results|
	#   if geo = results.first
	#     obj.city    = geo.city
	#     obj.zipcode = geo.postal_code
	#     obj.country = geo.country_code
	#   end
	# end
	# after_validation :reverse_geocode
end

app/models/tire.rb
class Tire < ActiveRecord::Base
end

app/models/tire_rebate.rb
class TireRebate < ActiveRecord::Base
end

app/models/tire_size.rb
class TireSize < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/models/wheel.rb
class Wheel < ActiveRecord::Base
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base

	def zipcode_full
		self.zipcode + '-' + self.city + ', ' + self.state
	end
	
end

app/helpers/carts_helper.rb
module CartsHelper
	# require 'active_shipping'	

 #  def origin
 #    Location.new(country: "US", state: "CA", city: "Los Angeles", postal_code: "90001")
 #  end

 #  def destination
 #    # Location.new(country: country, state: state, city: city, postal_code: postal_code)
 #  	Location.new(country: "US", state: "CA", city: "Beverly Hills", postal_code: "90210")
 #  end

 #  def packages
 #    package = Package.new(25, [24, 24, 9], units: :imperial)
 #  end

 #  def get_rates_from_shipper(shipper)
 #    response = shipper.find_rates(origin, destination, packages)
 #    response.rates.sort_by(&:price)
 #  end

 #  def ups_rates
 #    ups = UPS.new(login: 'your ups login', password: 'your ups password', key: 'your ups xml key')
 #    get_rates_from_shipper(ups)
 #  end

 #  def fedex_rates
 #    fedex = FedEx.new(login: "reynanalbaredo", password: "flynnriley2018", key: "q41znXQdFHQ2cVrJ", account: "510087500")
 #    get_rates_from_shipper(fedex)
 #  end

 #  def usps_rates
 #    usps = USPS.new(login: 'your usps account number', password: 'your usps password')
 #    get_rates_from_shipper(usps)
 #  end
end

app/helpers/tires_helper.rb
module TiresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidemenu.slim
nav.navbar.navbar-dark.fixed-top.bg-dark.flex-md-nowrap.p-0.shadow
  a.navbar-brand2.col-sm-3.col-md-2.mr-0 href="#"  ONLINE TIRES
  / input.form-control.form-control-dark.w-100 aria-label="Search" placeholder="Search" type="text" /
  ul.navbar-nav.px-3
    li.nav-item.text-nowrap
      a.nav-link href="#"  Sign out
.container-fluid
  .row
    nav.col-md-2.d-none.d-md-block.bg-light.sidebar
      .sidebar-sticky
        br
        ul.nav.flex-column
          li.nav-item
            = link_to ("<span data-feather='file'></span> Brands").html_safe, admin_brands_path(), class: 'nav-link'
            / a.nav-link.active href="#" 
            /   span data-feather="home" 
            /   | Dashboard
            /   span.sr-only (current)
          li.nav-item
            = link_to ("<span data-feather='file'></span> Models").html_safe, admin_brand_models_path(), class: 'nav-link'
          li.nav-item
            = link_to ("<span data-feather='file'></span> Categories").html_safe, admin_cms_categories_path(), class: 'nav-link'
          li.nav-item
            = link_to ("<span data-feather='file'></span> Reviews").html_safe, admin_reviews_path(), class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i" rel="stylesheet">
  <title>Online Tires</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application'%>
</head>
<body>
  <%= yield %>
</body>
</html>